version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/app
    restart: always
    networks:
      - api
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springtraining
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
  department-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    networks:
      - api
    ports:
      - "9080:9080"
    depends_on:
      - "mysql"
volumes:
  db_data:
networks:
  api:
