spring:
    application:
        name: SimpleRestService
    profiles:
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: mysql
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.187.1:3306/testdb?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
server:
    port: 8888


logging:
  level:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE


