spring:
    application:
        name: SimpleRestService
    profiles:
        # it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: h2
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:testdb
        username: dbuser
        password: letmein
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
server:
    port: 8888


logging:
  level:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE

# ===================================================================
# Application specific properties
# ===================================================================


