CREATE TABLE PUBLIC.DEPARTMENTS (DEPARTMENT_ID BIGINT NOT NULL auto_increment, DEPARTMENT_NAME VARCHAR(40) NOT NULL, 
CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID));

CREATE UNIQUE INDEX PUBLIC.IDX_DEPARTMENTS ON PUBLIC.DEPARTMENTS(DEPARTMENT_ID);

CREATE TABLE PUBLIC.EMPLOYEES (EMPLOYEE_ID BIGINT NOT NULL auto_increment, FIRST_NAME VARCHAR(20) NOT NULL, LAST_NAME VARCHAR(20) NOT NULL,
 EMAIL VARCHAR(20) NOT NULL, GENDER CHAR NOT NULL, AGE BIGINT NOT NULL, PHONE_NUMBER VARCHAR(20) NOT NULL, 
 DEPARTMENT_ID_FK  BIGINT NOT NULL, HIRE_DATE DATE NOT NULL, SALARY BIGINT(20) NOT NULL,
 CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID));

CREATE UNIQUE INDEX PUBLIC.IDX_EMPLOYEES ON PUBLIC.EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE PUBLIC.EMPLOYEES ADD CONSTRAINT EMPLOYEES_FK FOREIGN KEY (DEPARTMENT_ID_FK) REFERENCES PUBLIC.DEPARTMENTS (DEPARTMENT_ID);

CREATE SEQUENCE PUBLIC.DEPARTMENTS_SEQ;

CREATE SEQUENCE PUBLIC.EMPLOYEES_SEQ;


 
 